{'Backend': 'Catapult',
 'ClockPeriod': 5,
 'HLSConfig': {'LayerName': {'fc1': {'Precision': {'bias': 'ac_fixed<6,1,true>',
                                                   'weight': 'ac_fixed<6,1,true>'},
                                     'ReuseFactor': 1,
                                     'Trace': True},
                             'fc1_input': {'Precision': {'result': 'ac_fixed<16,6,true>'},
                                           'Trace': True},
                             'fc2': {'Precision': {'bias': 'ac_fixed<6,1,true>',
                                                   'weight': 'ac_fixed<6,1,true>'},
                                     'ReuseFactor': 1,
                                     'Trace': True},
                             'fc3': {'Precision': {'bias': 'ac_fixed<6,1,true>',
                                                   'weight': 'ac_fixed<6,1,true>'},
                                     'ReuseFactor': 1,
                                     'Trace': True},
                             'output': {'Precision': {'bias': 'ac_fixed<6,1,true>',
                                                      'weight': 'ac_fixed<6,1,true>'},
                                        'ReuseFactor': 1,
                                        'Trace': True},
                             'relu1': {'Precision': {'result': 'ac_fixed<7,1,true,AP_RND_CONV,AP_SAT>'},
                                       'ReuseFactor': 1,
                                       'Trace': True},
                             'relu2': {'Precision': {'result': 'ac_fixed<7,1,true,AP_RND_CONV,AP_SAT>'},
                                       'ReuseFactor': 1,
                                       'Trace': True},
                             'relu3': {'Precision': {'result': 'ac_fixed<7,1,true,AP_RND_CONV,AP_SAT>'},
                                       'ReuseFactor': 1,
                                       'Trace': True},
                             'softmax': {'Precision': 'ac_fixed<16,6,false>',
                                         'ReuseFactor': 1,
                                         'Trace': True,
                                         'exp_table_t': 'ac_fixed<18,8,true>',
                                         'inv_table_t': 'ac_fixed<18,4,true>',
                                         'table_size': 1024}},
               'Model': {'Precision': 'ac_fixed<16,6,true>',
                         'ReuseFactor': 1,
                         'Strategy': 'Latency'}},
 'IOType': 'io_parallel',
 'KerasH5': 'keras/qkeras_3layer_weights.h5',
 'KerasJson': 'keras/qkeras_3layer.json',
 'OutputDir': 'my-ccs-test',
 'ProjectName': 'myproject',
 'Part': 'xcku115-flvb2104-2-i',
 'XilinxPart': 'xcku115-flvb2104-2-i'}

