{'Backend': 'Vivado',
 'ClockPeriod': 5,
 'HLSConfig': {'LayerName': {'fc1': {'Precision': {'bias': 'ap_fixed<6,1>',
                                                   'weight': 'ap_fixed<6,1>'},
                                     'ReuseFactor': 1,
                                     'Trace': True},
                             'fc1_input': {'Precision': {'result': 'ap_fixed<16,6>'},
                                           'Trace': True},
                             'fc2': {'Precision': {'bias': 'ap_fixed<6,1>',
                                                   'weight': 'ap_fixed<6,1>'},
                                     'ReuseFactor': 1,
                                     'Trace': True},
                             'fc3': {'Precision': {'bias': 'ap_fixed<6,1>',
                                                   'weight': 'ap_fixed<6,1>'},
                                     'ReuseFactor': 1,
                                     'Trace': True},
                             'output': {'Precision': {'bias': 'ap_fixed<6,1>',
                                                      'weight': 'ap_fixed<6,1>'},
                                        'ReuseFactor': 1,
                                        'Trace': True},
                             'relu1': {'Precision': {'result': 'ap_fixed<7,1,AP_RND_CONV,AP_SAT>'},
                                       'ReuseFactor': 1,
                                       'Trace': True},
                             'relu2': {'Precision': {'result': 'ap_fixed<7,1,AP_RND_CONV,AP_SAT>'},
                                       'ReuseFactor': 1,
                                       'Trace': True},
                             'relu3': {'Precision': {'result': 'ap_fixed<7,1,AP_RND_CONV,AP_SAT>'},
                                       'ReuseFactor': 1,
                                       'Trace': True},
                             'softmax': {'Precision': 'ap_ufixed<16,6>',
                                         'ReuseFactor': 1,
                                         'Trace': True,
                                         'exp_table_t': 'ap_fixed<18,8>',
                                         'inv_table_t': 'ap_fixed<18,4>',
                                         'table_size': 1024}},
               'Model': {'Precision': 'ap_fixed<16,6>',
                         'ReuseFactor': 1,
                         'Strategy': 'Latency'}},
 'IOType': 'io_stream',
 'KerasH5': 'keras/qkeras_3layer_weights.h5',
 'KerasJson': 'keras/qkeras_3layer.json',
 'OutputDir': 'my-hls-test-stream',
 'ProjectName': 'myproject',
 'Part': 'xcku115-flvb2104-2-i',
 'XilinxPart': 'xcku115-flvb2104-2-i'}

